globally-unique-wrappers = true

[conda.bifo-essential]
wrapperdir = "~/wrappers/bifo-essential-wrappers"
envdir = "/stash/miniconda3/envs/bifo-essential"
public = [
    "blastall",
    "bwa",
]

[virtualenv.exec-wrappers]
wrapperdir = "~/wrappers/exec-wrappers"
envdir = "~/virtualenvs/exec-wrappers"
public = [
    "create-wrappers",
]
